### ISSUE TITLE
Remove @author tags

### ISSUE THREAD

**Issue by zhedar** [corona-warn-app/cwa-verification-server#62] opened 2020-05-25 16:18 UTC
## Current Implementation

Currently the javadoc class comments contain a `@author T-Systems International GmbH` tag, which doesn't add any information and is just additional clutter.

## Suggested Enhancement

Remove the tags.

## Expected Benefits

Let author information be handled by git, which does a much better job than a generic tag. Also there's already an [CODEOWNERS](https://github.com/corona-warn-app/cwa-verification-server/blob/master/CODEOWNERS) file.

**Comment by zhedar** [comment] 2020-05-25 19:36
If this is approved, we could also add a checkstyle rule like [Gradle](https://github.com/gradle/gradle/commit/a1b9612fa06f90f20b115cede557e22287501034#diff-8cb95faaaa6ece87877ab28d9a45bf36) did.

**Comment by WilliamLin** [comment] 2020-05-26 02:14
Hi,  I am new to the open-source and I would like to start to make the contribution by picking up some simple task, please assign this task to me or any low hanging fruit to me. Thanks

**Comment by kreincke** [comment] 2020-05-27 07:37
Please, let me comment on this issue in greater detail: 
Yes, you are right. For the moment, we have 9 files tagged with the JavaDoc tag '@author'. In each of these cases the value of this tag is 'TSI'. That's not very informative. Additionally and vice versa, not all files use the author tag. Nevertheless, I want to speak for preserving the state as it is. Let me explain the background:
For two reasons, it is unfortunately not sufficient to let only GIT handle the author = copyright information:
* The Apache-v2 license offers one place to add author and copyright information. That's the NOTICE file. Therefore, our version of this file contains a section 'contributors' into which each contributor can add his name if he is a real copyright owner (not all modifications are copyrightable: by fixing a typo you do not gain 'Miturheber-' or 'Bearbeiterurheberrechte').
* In a court case in Cologne a few years ago, the judge explained, that proving one's copyright ownership by the Github history alone mostly is not sufficient. Therefore, all our code files are opened by a header containing a copyright statement and a licensing statement.
The last point is very important for the community. The people outside in the world want to be sure that they really have the rights the Apache license seems to grant to them. But that's only valid if the real copyright owner (in this case: Deutsche Telekom AG / T-Systems Internation GmbH) is licensing the files under the Apache license.
Now we have to consider one last part of the European/German 'Urheberrecht': Whenever I program a piece of software (during my working time), the copyrights (Verwertungsrechte) are transferred to my company. That's part of my contract. All copyrights? No: there's one copyright that can never be transferred. That's the right to be named as an author. This right remains with me. But I can refrain from being named - for example in the author tag. Nevertheless, other copyrights belong to my company. And therefore, on the JavaDoc level, it could additionally be meaningful for the community to know that the author/copyright owner is T-Systems International GmbH and that they, therefore, have the rights, the Apache license promise to grant.
Such a simple case and such a long comment :)
To be concrete:
 @WilliamLin , it is very kind to offer your help. Of course, you technically will be able to erase the author-tags or to add the missed tags in the other files. But deleting / modifying copyright/author information by any other person than the copyright owner is either forbidden by the licenses or makes the copyright information doubtful. In the very near future, there will be published other repos and I am sure that you there will find appropriate tasks
@zhedar Based on the background I explained I tend to decide to let the files as they are, But of course, I will communicate into our team to make the JavaDoc comments a bit more speaking.
Before closing this issue, I am looking forward to reading your comments. 
Best regards

**Comment by zhedar** [comment] 2020-05-27 09:36
Thanks for your insight, Karsten. Your detailed answer is very appreciated.

> Therefore, all our code files are opened by a header containing a copyright statement and a licensing statement.

I agree about that. I think that's common practice.

Anyway I tried to have a quick look at the current legal situation by lookup up some court rulings to find your referenced case and found some other interesting court rulings.

For example there is an interesting ruling from OLG Hamburg I'd like to share for anyone who reads this and is interested:

> OLG Hamburg, Urteil v. 28.02.2019, Az. 5 U 146/16
> Aktivlegitimation von Bearbeiterurhebern einer GPL-lizenzierten Software
> Link: https://dejure.org/ext/59ddbf2dfc895af3f8e6b13d9cb65bf8

See 67:
> [Re][...] Ein Sachverständiger wäre damit in der Lage nachzuvollziehen, welche Code-Bestandteile ursprünglich von ihm, dem Kläger, stammten, wie diese in der Linux-Entwicklung über Jahre verändert worden seien und weiterhin relevant im Quellcode der Beklagten auffindbar seien.

Which says, that git history (or in this specific case some tool, which combines information from different version control systems) is sufficient to prove code ownership (as in who created the code).

However back to the core problem:

> Nevertheless, other copyrights belong to my company. And therefore, on the JavaDoc level, it could additionally be meaningful for the community to know that the author/copyright owner is T-Systems International GmbH and that they, therefore, have the rights, the Apache license promise to grant.

I see, but wouldn't everybody need to refrain from these naming right every time a change is made? I'm not sure, if the author tags really solves that as it is only added once and not reconfirmed on every change.


Anyway, to wrap this up, I dont want this formality to block any critical progress. However as I would really like to see more public open source projects like this, these discussions might be of value in the future. For now, I'm ok with leaving it as it is and focusing on getting this production ready first.

**Comment by martinmuellerrohde** [comment] 2020-05-27 09:39
All author tags seem to be remove in #82 .
I think this is a good change.
@kreincke your concerns seem to apply for a copyright noticve but I guess an author-tag is not really required. But I might be wrong here. In that case you need to add'em again.....

**Closed** 2020-05-28 06:45 UTC
Labels: enhancement, in progress

**Comment by daniel-eder** [comment] 2020-05-28 06:51
The author tags are indeed a duplicate of the copyright notice in the file, therefore they are now removed. 

The copyright notices, however, need to remain  - the case referenced by @zhedar actually concludes that the reason in 67 (brought forth by the plaintiff) is not sufficient (alleged by the defendant in 81, clarified by the court in 114) and the court ruled against the plaintiff. 

While this is not the right place for a lengthy legal argument, I do appreciate the effort in researching the cases (and welcome further material), this topic is of ongoing interest in the open source community.
